export function renderNotices(data, exceptions, version) {
let out = `# Third-party notices for Fairbeam ${version}\n\nGenerated by scripts/third-party-licenses.mjs. Do not edit this file.\n\nRegenerate with \`node scripts/third-party-licenses.mjs --refresh\`; check offline with\n\`npm run check:licenses\`. Metadata and original license/NOTICE texts are preserved in\n\`scripts/licenses/inventory.json\`. No additional npm dependencies are needed.\n\nThe Rust section follows normal dependencies for the locked default-feature desktop graph\non macOS arm64, Windows x64 and experimental Linux x64 packages, excluding build tooling, tests and proc-macro implementations. The viewer section uses Vite's rendered modules\nplus shipped font packages. Runtime components are downloaded on first start, separately from\nthe installer. Linux system libraries and the user-managed external Linux solver environment are not bundled. Versions below describe the inputs of this release, not a user's custom runtime.\n\n`;
for (const section of data.sections) {
  out += `## ${section.title}\n\n${section.description || ''}\n\n`;
  for (const p of section.packages) {
    const key = `${p.ecosystem}:${p.name}@${p.version}`;
    if (!p.license || /unknown|missing|NOASSERTION/i.test(p.license)) {
      if (!exceptions[key]) throw new Error(`Missing or unknown license: ${key}`);
    }
    if (!p.texts.length && !exceptions[key]) throw new Error(`No license text: ${key}`);
    out += `### ${p.name} ${p.version}\n\nLicense: ${p.license || 'Review pending'}. Source: ${p.source}.\n\n`;
    if (p.evidence) out += `${p.evidence}\n\n`;
    if (exceptions[key]) out += `Reviewed exception: ${exceptions[key]}\n\n`;
    for (const t of p.texts) out += `<details>\n<summary>${t.name.replaceAll('<','&lt;')}</summary>\n\n\`\`\`text\n${t.text.trim().replace(/\r\n?/g, '\n').replace(/[ \t]+$/gm, '')}\n\`\`\`\n\n</details>\n\n`;
  }
}
return out.trimEnd() + "\n";
}
